help :-
    write(' _     _    _______    _          ______'), nl,
    write('| |   | |  |  _____|  | |        |  __  \\'), nl,
    write('| |   | |  | |_____   | |        | |__|  |'), nl,
    write('| ----- |  |       |  | |        |  ____/'), nl,
    write('| ----- |  |  _____|  | |        | |'), nl,
    write('| |   | |  | |_____   | |_____   | |'), nl,
    write('|_|   |_|  |_______|  |_______|  |_|'), nl, nl, nl, nl,
    write('------------- COMMAND UMUM -------------'), nl,
    write('startgame : untuk memulai petualanganmu                       '), nl,
    write('map       : menampilkan peta                                  '), nl,
    write('status    : menampilkan kondisimu terkini                     '), nl,
    write('w         : gerak ke utara 1 langkah                          '), nl,
    write('s         : gerak ke selatan 1 langkah                        '), nl,
    write('d         : gerak ke ke timur 1 langkah                       '), nl,
    write('a         : gerak ke barat 1 langkah                          '), nl,
    write('inventory : menampilkan status pemain                         '), nl,
    write('help      : menampilkan segala bantuan                        '), nl,
    write('quit      : keluar dari permainan                             '), nl, nl, nl,
    write('---------------- BATTLE ----------------'), nl,
    write('Dalam battle pemain dan musuh akan saling menyerang secara bergantian.'), nl,
    write('%%%%%%%%% COMMAND DALAM BATTLE %%%%%%%%%'), nl,nl,
    write('attack           : Pemain menyerang lawan dengan kekuatan biasa.'), nl,
    write('specialattack    : Pemain menyerang lawan dengan kekuatan lebih dari serangan biasa.'), nl,
    write('usepotion        : Pemain menggunakan potion dalam battle.'), nl,
    write('run              : Pemain mencoba melarikan diri dari musuh.'), nl, nl,nl,
    write('----------------  SHOP  ----------------'), nl,
    write('Dalam shop pemain dapat melakukan pembelian potion, gacha aksesoris, dan gacha senjata.'), nl,nl,
    write('%%%%%%%%%  COMMAND DALAM SHOP  %%%%%%%%%'), nl,
    write('shop             : Pemain memasuki shop.'), nl,
    write('gacha            : Pemain melakukan gacha senjata yang akan didapatkan.'), nl,
    write('exitshop         : Pemain keluar dari shop.'), nl,
    write('Untuk potion, pemain dapat memilih secara langsung.'), nl, nl.

    
